"""Offline Vulkan graphics shaders; no compiler needed by the shipped game."""
import argparse
import hashlib
import pathlib
import struct
import subprocess
import tempfile

parser = argparse.ArgumentParser()
parser.add_argument('--dxc')
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
root = pathlib.Path(__file__).resolve().parents[1]
source = root / 'src/vr/shaders/scene.hlsl'
output = root / 'src/vr/shaders/scene_spirv.hpp'
dependencies = [source, root / 'include/starfox/render/ex_face_planet_regions.inc']
stamp = '// Source SHA-256: ' + hashlib.sha256(b''.join(
    path.read_bytes().replace(b'\r\n', b'\n') for path in dependencies)).hexdigest()
if args.check:
    if not output.exists() or stamp not in output.read_text().splitlines()[:3]:
        raise SystemExit('VR shaders stale; regenerate with DXC.')
    raise SystemExit(0)
if not args.dxc:
    parser.error('--dxc required for generation')
text = '// Generated by tools/generate_vr_shaders.py; do not edit.\n' + stamp + '\n#pragma once\n#include <cstdint>\nnamespace starfox::vr::shader {\n'
with tempfile.TemporaryDirectory() as temporary:
    for stage, profile in [('vertex', 'vs_6_0'), ('vertex_textured', 'vs_6_0'), ('fragment', 'ps_6_0'), ('fragment_textured', 'ps_6_0')]:
        binary = pathlib.Path(temporary) / (stage + '.spv')
        subprocess.run([args.dxc, '-spirv', '-fspv-target-env=vulkan1.0', '-T', profile,
                        '-E', stage + '_main', '-Fo', str(binary), str(source)], check=True)
        blob = binary.read_bytes()
        words = struct.unpack('<' + 'I' * (len(blob) // 4), blob)
        text += 'inline constexpr std::uint32_t ' + stage + '[]={\n'
        text += ',\n'.join(','.join(hex(v) for v in words[i:i+8]) for i in range(0, len(words), 8)) + '\n};\n'
text += '}\n'
output.write_text(text, encoding='utf-8', newline='\n')
